<?php
    echo "<p>"
        ."
        <h1>Nacistické  Německo</h1> se označuje německý stát v době vlády nacistické strany, tedy od roku 1933 (jmenování Adolfa Hitlera německým kancléřem proběhlo 30. ledna 1933 a diktátorské pravomoci Hitler převzal v březnu 1933) do kapitulace Německa na konci druhé světové války 8. května 1945. Oficiální název státu byl Německá říše (německy Deutsches Reich) do roku 1943 a Velkoněmecká říše (německy Großdeutsches Reich) od roku 1943 do jeho zániku roku 1945. K dalším užívaným označením nacistického Německa patří pojmy třetí říše, „národně-socialistický stát“ či „vůdcovský stát“. 
        Adolf Hitler se 30. ledna 1933 dostal legálně k moci, když byl dosazen do funkce říšského kane prezidentem tehdejšího Německa Paulem von Hindenburgem. Na začátku své vlády předsedal koaličnímu kabinetu, ale poměrně záhy se mu podařilo od vlády odstavit ty členy kabinetu, kteří nebyli členy nacistické strany. Po uchopení moci se povedlo nacistickému režimu opět postavit ekonomiku na nohy a ukončit vysokou nezaměstnanost pomocí masových investic do zbrojení. Návrat ekonomické prosperity vedl k nárůstu popularity režimu mezi německým obyvatelstvem, což se projevilo oddaností Němců režimu. 
        Opozice z řad liberálů, socialistů a komunistů byla tvrdě potlačována tajnou státní policií gestapem pod patronací Heinricha Himmlera. Nacistická strana postupně ovládla soudy, místní vlády a všechny občanské organizace kromě protestantských a katolických. Veřejné mínění v Říši utvářelo ministerstvo propagandy vedené Josefem Goebbelsem, který k tomu využíval masmédia, film a uhrančivé Hitlerovy projevy. Státní aparát se snažil vykreslit Hitlera jako vůdce německého lidu (Führer) a k tomu účelu mu předával do ruky veškerou výkonnou moc. 
        Na začátku existence nacistického Německa zaujal Hitler zahraniční politiku strachu a vydírání, vznášel zdánlivě důvodné požadavky na soucléřsední země, kterým v případě neplnění vyhrožoval válkou. Když se ho pokusili protivníci uklidnit ústupky, přijal je a zaměřil se na další oblast. Tímto postupem se mu podařilo získat značné území, aniž by to vedlo k válce (např. Mnichovská dohoda a odstoupení československého pohraničí Německu v roce 1938). Agresivní politika Německa vedla k vypovězení Versailleské smlouvy a od roku 1935 se Německo začalo znovu vyzbrojovat. Téhož roku si opět připojilo Sársko, o rok později remilitarizovalo Porýní, vytvořilo spojenectví – Osu – s fašistickou Itálií pod vládou Benita Mussoliniho, poslalo pomoc Frankovu fašistickému Španělsku, anektovalo Rakousko v roce 1938 a obsadilo již zmiňované československé pohraničí a později i zbytek Československa. Neustále rostoucí územní nároky vyvrcholily 1. září 1939 invazí do Polska, načež Francie a Velká Británie vyhlásily nacistickému Německu válku, čímž oficiálně začala druhá světová válka, dříve než nacistické Německo čekalo či na ni bylo zcela připraveno. 
        Během války se nacistickému Německu podařilo obsadit velkou část Evropy od Francie až téměř po Moskvu v tehdejším Sovětském svazu, dále od Norska na severu až po rozsáhlé pouštní oblasti v severní Africe na jihu. Na většině okupovaných území se nacisté pokusili zavést „Nový pořádek“. Současně začalo docházet k masovým persekucím neněmeckého obyvatelstva, vyvražďování Slovanů, cikánů a Židů, pro které se vžil termín holokaust. Během tohoto období zemřely miliony lidí. Nicméně v průběhu války se začala situace na frontě obracet v neprospěch nacistického Německa, což v důsledku vedlo k jeho porážce. Druhá světová válka v Evropě skončila 8. května 1945 kapitulací Německa západním spojencům a Sovětskému svazu. 
        "
    ."</p>";
?> 